### PR TITLE
EPR-864   Support multiple emails in Email Service

### PR DESCRIPTION
**Pull request by hshaosf**
Used SendGrid [Personalization](https://github.com/sendgrid/sendgrid-python/blob/2fe145956a1ee50355f5da8deab401e1e118c736/examples/helpers/mail_example.py#L28) to handle multiple emails

### CODE REVIEW

**Comment by hshaosf** [comment]
In this PR, I removed the `get_emails` method in the helper and used `Personalization` instead. When passing in arrays into the `message` directly, it was not worked as expected when there were multiple emails.

**Review by josh-chou — APPROVED** [review]
looks good!

**Comment by ds-derekchinn** [comment]
> When passing in arrays into the `message` directly, it was not working as expected when there were multiple emails.

Does this mean it _should've_ handled multiple email addresses to the 'to', but just didn't?


> apologies in advance to @ds-derekchinn for removing a chunk of his work in the previous [PR](https://github.com/SFDigitalServices/email-microservice-py/pull/21).

Meh - c'est la vie. As long as it does what we need it to do.

**Comment by hshaosf** [comment]
@ds-derekchinn that's right. in the previous implementation, we were following this [example](https://github.com/sendgrid/sendgrid-python/blob/2fe145956a1ee50355f5da8deab401e1e118c736/examples/helpers/mail_example.py#L161-L164). It turns out, it doesn't really work like we thought it would.

**Pull request merged**
